### ISSUE TITLE
Could not initialize SDL: No available video device

### ISSUE THREAD

**Issue by bluespacezero** [pierlon/scrcpy-docker#10]
/ # scrcpy
/usr/local/share/scrcpy/scrcpy-server....shed. 2.3 MB/s (18802 bytes in 0.008s)
CRITICAL: Could not initialize SDL: No available video device

I did run xhost + local:docker before run the image...why still resulting like that?

**Comment by bluespacezero** [comment]
/ # env | grep DISPLAY
DISPLAY=:0
/ #

**Comment by pierlon** [comment]
Duplicate of #5.

Does the command `xhost + local:docker` return something similar to: `non-network local connections being added to access control list`?

Also, what OS are you using?

**Comment by bluespacezero** [comment]
just as you said, but now it works well on my ubuntu 18.10..but i still don't konw why
