### ISSUE TITLE
CRITICAL: Could not create renderer: Couldn't find matching render driver

### ISSUE THREAD

**Issue by wernight** [pierlon/scrcpy-docker#6]
After resolving https://github.com/pierlon/scrcpy-docker/issues/5, I see this error:

    /usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 1.6 MB/s (18570 bytes in 0.011s)
    CRITICAL: Could not create renderer: Couldn't find matching render driver                                            
    ERROR: Could not open video stream

I tried amd, intel and nvidia with the same results.

I do `sudo docker ..` on Elementary OS on an AMD with a nVidia card.

**Comment by pierlon** [comment]
Fixed by PR #8.
