### ISSUE TITLE
Update Docker image

### ISSUE THREAD

**Issue by husimo** [pierlon/scrcpy-docker#9]
Hello,
It seems that Docker base image is not updated in Docker Hub.
I had previously this issue : https://github.com/pierlon/scrcpy-docker/issues/6 ; and I have been able to make it work building the base image using the Dockerfile provided.
Nonetheless I had to remove the last line of Dockerfile to make it build.
Thank you

**Comment by pierlon** [comment]
Thanks for letting me know @husimo, Docker Hub images are update now :smile:
